/*
 * module function declaration for library randommod header (autogenerated)
 */

#include "randommod_module.h"

int randommod_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=random_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void randommod_mod_cleanup(ubx_node_info_t* ni)
{
  random_mod_cleanup(ni);
}

